// A curated subset of Google Places API "included types" that are common
// B2B lead-gen categories (https://developers.google.com/maps/documentation/places/web-service/place-types).
// If the user's keyword matches one of these exactly (case-insensitive, spaces
// or underscores), we use Nearby Search (New), which is optimized for
// category browsing. Otherwise we fall back to Text Search (New) with the
// keyword as a free-text query, which handles arbitrary phrases like
// "digital marketing agency" that have no matching Places type.
export const KNOWN_PLACE_TYPES = [
  "accounting",
  "airport",
  "amusement_park",
  "aquarium",
  "art_gallery",
  "atm",
  "bakery",
  "bank",
  "bar",
  "beauty_salon",
  "bicycle_store",
  "book_store",
  "bowling_alley",
  "cafe",
  "car_dealer",
  "car_rental",
  "car_repair",
  "car_wash",
  "casino",
  "cemetery",
  "church",
  "clothing_store",
  "convenience_store",
  "courthouse",
  "dentist",
  "department_store",
  "doctor",
  "drugstore",
  "electrician",
  "electronics_store",
  "embassy",
  "fire_station",
  "florist",
  "funeral_home",
  "furniture_store",
  "gas_station",
  "gym",
  "hair_care",
  "hardware_store",
  "hindu_temple",
  "home_goods_store",
  "hospital",
  "insurance_agency",
  "jewelry_store",
  "laundry",
  "lawyer",
  "library",
  "liquor_store",
  "local_government_office",
  "locksmith",
  "lodging",
  "mosque",
  "movie_theater",
  "moving_company",
  "museum",
  "night_club",
  "painter",
  "park",
  "parking",
  "pet_store",
  "pharmacy",
  "physiotherapist",
  "plumber",
  "police",
  "post_office",
  "real_estate_agency",
  "restaurant",
  "roofing_contractor",
  "rv_park",
  "school",
  "shoe_store",
  "shopping_mall",
  "spa",
  "stadium",
  "storage",
  "store",
  "supermarket",
  "synagogue",
  "taxi_stand",
  "tourist_attraction",
  "travel_agency",
  "university",
  "veterinary_care",
  "zoo",
] as const;

export type KnownPlaceType = (typeof KNOWN_PLACE_TYPES)[number];

export function matchKnownPlaceType(keyword: string): KnownPlaceType | null {
  const normalized = keyword.trim().toLowerCase().replace(/[\s-]+/g, "_");
  return (KNOWN_PLACE_TYPES as readonly string[]).includes(normalized)
    ? (normalized as KnownPlaceType)
    : null;
}
